name: panache_ui
description: A new Flutter project.
version: 0.0.1
author:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  panache_core:
    path: ../panache_core

  provider: ^4.3.3

  #panache_services:
    #path: ../panache_services

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - github.png
